function(target_compile_warn_all IN_TARGET_NAME)
	if (MSVC)
		target_compile_options(${IN_TARGET_NAME} PRIVATE "/W4")
	else()
		target_compile_options(${IN_TARGET_NAME} PRIVATE "-Wall")
	endif()
endfunction(target_compile_warn_all IN_TARGET_NAME)