name: CMake

on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build-cmake.yml"
      - "**/*.c"
      - "**/*.h"
      - "**/CMakeLists.txt"
      - "cmake/*.cmake"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/build-cmake.yml"
      - "**/*.c"
      - "**/*.h"
      - "**/CMakeLists.txt"
      - "cmake/*.cmake"

jobs:
  linux-build-cmake:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        preset: ["linux-gcc", "linux-clang"]
    steps:
      - uses: actions/checkout@v5
      - name: Install Build Dependencies
        run: echo | python "${{ github.workspace }}/bin/acquire_epos_cmdlib.py"
      - name: Setup CMake
        run: |
          cmake -S . -B build --preset=${{ matrix.preset }}
      - name: Build
        run: |
          cmake --build build

  windows-build-cmake:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        preset: ["windows-mingw"] #, "cl.exe"]
    steps:
      - uses: actions/checkout@v5
      #- uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Install Build Dependencies
        run: echo "" | python "${{ github.workspace }}/bin/acquire_epos_cmdlib.py"
      - name: Setup CMake
        run: |
          cmake -S . -B build --preset=${{ matrix.preset }}
      - name: Build
        run: |
          cmake --build build
