name: Meson

on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build-meson.yml"
      - "ipc/**/*.c"
      - "ipc/**/*.h"
      - "test/*.c"
      - "**/meson.build"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/build-meson.yml"
      - "ipc/**/*.c"
      - "ipc/**/*.h"
      - "test/*.c"
      - "**/meson.build"

jobs:
  linux-build-meson:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        compiler: ["gcc", "clang"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13.0"
      - name: Install Build Dependencies
        run: |
          pip3 install meson ninja
          sudo apt install patchelf -y
          echo | python "${{ github.workspace }}/bin/acquire_epos_cmdlib.py"
      - name: Setup Meson
        run: |
          CC=${{ matrix.compiler }} meson setup build
      - name: Build
        run: |
          CC=${{ matrix.compiler }} meson compile -C build
      - name: Verbosely Test
        run: |
          LD_LIBRARY_PATH=$(realpath build/test) meson test -v -C build
        # above is a HACK!!
        
  windows-build-meson:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        compiler: ["gcc.exe"] #, "cl.exe"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13.0"
      #- uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Install Build Dependencies
        shell: "pwsh"
        run: |
          pip3 install meson ninja
          echo "" | python "${{ github.workspace }}/bin/acquire_epos_cmdlib.py"
      - name: Setup Meson
        run: |
          meson setup build
        env:
          CC: ${{ matrix.compiler }}
      - name: Build
        run: |
          meson compile -C build
        env:
          CC: ${{ matrix.compiler }}
      - name: Verbosely Test
        run: |
          meson test -v -C build
