name: Build

on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build.yml"
      - "ipc/**/*.c"
      - "ipc/**/*.h"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/build.yml"
      - "ipc/**/*.c"
      - "ipc/**/*.h"

jobs:
  linux-build-meson:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13.0"
      - name: Install Build Dependencies
        run: |
          pip3 install meson ninja
      - name: Setup Meson
        run: |
          meson setup build
      - name: Build
        run: |
          meson compile -C build
