name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types: ["completed"]

jobs:
  meson-test:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: "${{ github.event.workflow_run.head_repository.full_name }}"
          ref: "${{ github.event.workflow_run.head_branch }}"
      - name: Verbosely Test
        run: |
          meson test -v -C build
